### ISSUE TITLE
PJON v12.0 support

### ISSUE THREAD

**Issue by gioblu** [Galitskiy/PJON-gRPC#2]
Ciao @Halytskyi :)
How is the setup behaving? All fine?
Soon v12.0 will be released, do you plan to update PJON-gRPC to support it?
If so, in master you find the code :)

**Comment by Halytskyi** [comment]
Ciao @gioblu :)
Was very busy last year... After quick check I see that PJON-gRPC doesn't support v12.0 for now. Will fix it in next few days :)

**Comment by Halytskyi** [comment]
PJON-gRPC support 12.0 PJON version now.
Documentation updated.
